language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2

script:
  - export TEST_MODE=TRAVIS
  - export NS_HOSTNAME=$NS_HOSTNAME
  - export NS_KEYNAME=$NS_KEYNAME
  - export NS_KEY=$NS_KEY
  - export NS_CPCODE=$NS_CPCODE 
  - ruby test/test_netstorage.rb