language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2

env:
  global:
    - secure: mDQ366ERNQSLoIqdd1gQPfeZAJvoc6J+iPTaB4BULUtcuU7Y7SgJSbm8COf97O7YA8D7hJV3NpaqbwO6T1Bl5VCpx5M70RvhnvFxNKcSVRnWvinE2QoakriBkyrU09aSSuFcROQehMgknEzM+eobjHBThHWhv68KBPduExfBU4/rHM91Gp5SNAkgmUiuFLVn3X4etWNdlEPE9zYRFJvRHWzMYq4OsC+4wWxP2B21bxT4aXBMuwITCbKmRFWZ2Noa1itOkA2oxqJLhNuTbvIBL2vDaCUnFRZ1iT/lZISQBv9yyocBQuimBzbBK7GL4BWz1MZOIpRniZQ+I1t/uPEYXHDrQ6tx1tS4gPwMYbdRmyo8EmWwG5CiGFaLYLqkEBfAxQSUCrhZt547kdnqZgpSxAmFBjGxSlt/5P/1fmmWGeJSUj/U0FD0Nm9JDjMxtF2xCUsrBi6/HW7+9Pgv9UC4XhHDRgmPKUA5BkSD9kIEoV5hhEYQMOQLmLyvM6CePwgZHNOL3aYFHcfZmuE05UFgl/V6Eat1+JebkeX8cKZEOiZk504MS1zZPFd/Z7NZxwS+U/lsjDnEYd+dUR2Nbe++GQny19PvGL5k6nNKa5HHB8k9fBc+8Oh/8YCMN+9XQ0JhcYUbjIq7eT9xeneCYEWkvpiih+6IjIKlQHhvKvyE8Ks=

script:
  - export TEST_MODE=TRAVIS
  - export NS_HOSTNAME=$NS_HOSTNAME
  - export NS_KEYNAME=$NS_KEYNAME
  - export NS_KEY=$NS_KEY
  - export NS_CPCODE=$NS_CPCODE 
  - ruby test/test_netstorage.rb